version: 2
jobs:
  build:

    working_directory: ~/springmockk

    docker:
      - image: cimg/openjdk:17.0.3

    steps:

      - checkout
      - run: ./gradlew build
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/libs/
